### ISSUE TITLE
Requireing other file does not work if wright bin is called

### ISSUE THREAD

**Issue by joerg** [sometimesfood/wright#11]
```
root@5bf941d86755:/tmp/kitchen# wright wright.rb 
root@5bf941d86755:/tmp/kitchen# ruby wright.rb 
INFO: create directory: '/tmp/foo2'
INFO: create symlink: '/tmp/foo2/fstab' -> '/etc/fstab'
```

The wright.rb has an `require './lib/someother.rb'`

Calling wright scripts through the binary would be nice because of the verbosity (and possibly other future) options.

**Comment by sometimesfood** [comment]
Thanks for the bug report. Just as a temporary workaround, please try renaming `wright.rb` to literally anything else.

What's going on here? Try running `wright wright.rb` without having a file called `wright.rb`. It will never fail because wright always loads its own wright.rb (i.e. [lib/wright.rb](https://github.com/sometimesfood/wright/blob/e44d875c4bb4ee25c91c46ab03f8de00d53d70c7/lib/wright.rb)).

The bug here seems to be that wright cannot currently load files called `wright` or `wright.rb` because we are missing a `File.expand_path` in [Wright::CLI#run_script](https://github.com/sometimesfood/wright/blob/e44d875c4bb4ee25c91c46ab03f8de00d53d70c7/lib/wright/cli.rb#L41-L42).

I'll push out a new version tomorrow.
